version: '3.4'

services:
    catalogdb:
        image: mongo

    basketdb:
        image: redis

    rabbitmq:
        image: rabbitmq:3-management-alpine
    
    catalog.api:
        image: catalog.api
        build:
            context: .
            dockerfile: src/Catalog/Catalog.API/Dockerfile
    
    basket.api:
        image: basket.api
        build:
            context: .
            dockerfile: src/Basket/Basket.API/Dockerfile
